### PR TITLE
Update JrjcJiraClient.groovy

### PR DESCRIPTION
**Pull request by dougjoh**
Error Timeout Waiting for task, when is many jobs with the generic filter (about 600 +)

### CODE REVIEW

**Comment by ceilfors** [comment]
Thanks for the PR!

Can you elaborate more about what you are trying to fix? What do you mean by 'generic filter'? Is there anything that we can do to make this more configurable?

**Comment by dougjoh** [comment]
Error

**Comment by dougjoh** [comment]
Im use This plugin to link project jira with pipeline and multjobs Jenkins.

Into job we use the option build when an issue is update in jira and into jql filter we use project= project Key jira and issuetype=xxx
Changelog matcher compare field state

So, we have about 600 multjobs and pipeline running query into jira. When jira delay occurs, the plugin stop with the error timeout

**Comment by dougjoh** [comment]
Change time help to process all tasks

**Comment by ceilfors** [comment]
From your use case, you should be able to use Change log matcher capability to compare project and issuetype, hence the JQL filter should not be needed. I think that would be a better solution for you as you'll not be bombarding JIRA with a lot of requests. What do you think?

**Comment by dougjoh** [comment]
we tried to use the change log matcher but it did not work. Apparently the JSON does not contain the data of the unchanged fields in the jira or can not compare the project key with the previous value or the new value because not change the key

**Comment by ceilfors** [comment]
You are right, I have remembered wrongly. For the PR, would you like to try to make this value more configurable? I'm also thinking that it might be best to rate limit the requests to JIRA to make sure that we are not exhausting the JIRA instance.

**Comment by dougjoh** [comment]
Is the best solution but im not a delevoper, i cant help

**Comment by ceilfors** [comment]
Apologies that I can't merge this PR as eventually you will need to increase the number again if you have hit the upper limit e.g. more than 600 multijobs for example. The solution is too specific for your problem.

Since you are not a developer, I'd suggest filing a feature request in [JENKINS issue tracker](https://issues.jenkins-ci.org/secure/Dashboard.jspa) with `jira-trigger-plugin` component.

**Pull request closed without merging**
