### PR TITLE
JENKINS-58987 Update dependency to jira-rest-java-client-core:5.2.1

### PR DESCRIPTION
**Pull request by zztalker**
Continuing @rodrigc pull request #6

### CODE REVIEW

**Comment by zztalker** [comment]
Hello, @ceilfors Can you review this?

**Comment by zztalker** [comment]
@oleg-nenashev Could you take a look?

**Comment by ceilfors** [comment]
_Apologies for my slow reply, for some reason GitHub has no longer send a notification to my email! Still figuring out how to fix this_

Thanks for the PR! This is looking great. A lot of people are looking for this fix. I'm merging this and will release this now. Please let me know if this fixes the issue for you at JENKINS-58987 :)

**Comment by ceilfors** [comment]
@all-contributors please add zztalker for code

**Comment by ceilfors** [comment]
@all-contributors please add rodrigc for code

**Comment by halkeye** [comment]
> _Apologies for my slow reply, for some reason GitHub has no longer send a notification to my email! Still figuring out how to fix this_

looks like your not watching the repo

**Comment by ceilfors** [comment]
@halkeye I am though, I can see it the watcher list https://github.com/jenkinsci/jira-trigger-plugin/watchers

**Pull request merged**
