### PR TITLE
Upgrade Gradle to 6.8.1 and jpi plugin to 0.42.0

### PR DESCRIPTION
**Pull request by sghill**
Hi,

I noticed the version of the jpi plugin was out of date and thought I'd take a look at upgrading it. The most recent jpi plugin versions require Gradle 6.x.

I moved everything to the plugins block because it's supported by all these plugins, and it's no longer necessary to include a jenkins repository for the buildscript.

## Strategy
My first strategy was to upgrade both to the latest version, but that build did not succeed. Next I wrote a script to increment Gradle and the jpi plugin. Going version-by-version let me use git bisect to figure out exactly when I couldn't upgrade without additional changes, and then isolate those changes in their own commit. 

I'd really appreciate your feedback on the number of commits. I found having lots of small commits extremely helpful for finding where a breaking change occurred, but I recognize 41 commits is a lot for a relatively small pull request. If you'd prefer the commits were all rebased into one, skipping changes that didn't require other updates, or something else - let me know and I'll be happy to update it.

## Publication Changes

To test everything after this change I published a snapshot to my local maven repository before and after the upgrades. Next, I compared these files:
```
jira-trigger-1.0.1-SNAPSHOT.jar
jira-trigger-1.0.1-SNAPSHOT-javadoc.jar
jira-trigger-1.0.1-SNAPSHOT.jpi
jira-trigger-1.0.1-SNAPSHOT.pom
jira-trigger-1.0.1-SNAPSHOT-sources.jar
```
The most interesting comparisons are what's within the `jar`s and `jpi`, so I listed the contents of each and saved them as a file for that:

```
$ find <repo> -type f -name "*.jar" -exec sh -c 'zipinfo -1 {} > {}.txt' \;
$ find <repo> -type f -name "*.jpi" -exec sh -c 'zipinfo -1 {} > {}.txt' \;
```

That left us with these identical files:

```
$ diff -rs before/ after/
Files before/jira-trigger-1.0.1-SNAPSHOT.jar.txt and after/jira-trigger-1.0.1-SNAPSHOT.jar.txt are identical
Files before/jira-trigger-1.0.1-SNAPSHOT-javadoc.jar.txt and after/jira-trigger-1.0.1-SNAPSHOT-javadoc.jar.txt are identical
Files before/jira-trigger-1.0.1-SNAPSHOT-sources.jar.txt and after/jira-trigger-1.0.1-SNAPSHOT-sources.jar.txt are identical
```

### jpi differences

The biggest change in the jpi is that `WEB-INF/classes/*` was replaced with `WEB-INF/lib/jira-trigger-1.0.1-SNAPSHOT.jar`. This is expected and was introduced in [jpi plugin v0.36.0](https://github.com/jenkinsci/gradle-jpi-plugin/releases/tag/v0.36.0) to better align with how the maven-hpi-plugin packages plugins.

Libraries are now added to the archive in a different order.

### pom differences

These differences all seem safe to me. Most of them can be attributed to leaning more on Gradle to generate the metadata by using its built-in configurations starting with [jpi plugin v0.39.0](https://github.com/jenkinsci/gradle-jpi-plugin/releases/tag/v0.39.0).

* The order of elements has changed, which can be attributed to [jpi plugin v0.31.0](https://github.com/jenkinsci/gradle-jpi-plugin/releases/tag/v0.31.0) using the [pom configuration dsl](https://docs.gradle.org/4.8/release-notes.html#customizing-the-generated-pom).
* Dependencies now include a specific scope of `compile` instead of relying on the default.
* `provided` dependencies are no longer included in the pom.
* Excluded groups now include `*` for the `artifactId` instead of empty element.
* Gradle now ships [its own metadata format](https://blog.gradle.org/gradle-metadata-1.0). The pom includes a comment to say it exists:

```xml
<!-- This module was also published with a richer model, Gradle metadata,  -->
<!-- which should be used instead. Do not delete the following line which  -->
<!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
<!-- that they should prefer consuming it instead. -->
<!-- do_not_remove: published-with-gradle-metadata -->
```

### CODE REVIEW

**Comment by sghill** [comment]
Build is failing on Windows, but it may be an agent issue?

```
java.io.IOException: Unable to delete 'C:\Users\jenkins\AppData\Local\Temp\j h8216213307882106516\jobs\job\builds\1'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at hudson.Util.deleteFile(Util.java:250)
	[ ... omitted ... ]
Caused by: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\AppData\Local\Temp\j h8216213307882106516\jobs\job\builds\1
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
```

**Comment by ceilfors** [comment]
Thanks @sghill. I'm a bit struggling at the moment to maintain this plugin. Would you be interested to become the maintainer of this plugin?

**Comment by sghill** [comment]
Hi @ceilfors, 

Unfortunately I'll have to decline becoming maintainer for now. I'm not a heavy user and I wouldn't be able to give this plugin much attention.

I'm happy to continue sending in PRs to update Gradle and the jpi plugin (I maintain the jpi plugin) if that's helpful.

**Comment by ceilfors** [comment]
@sghill Thanks for your kind response, this PR is definitely helpful, thanks for updating your downstream users!

**Pull request merged**
