### PR TITLE
JENKINS-58987 Update dependency to jira-rest-java-client-core:5.2.1

### PR DESCRIPTION
**Pull request by rodrigc**
Similar to the fix done here:
https://github.com/jenkinsci/jira-plugin/pull/213

for latest API changes done by Atlassian

### CODE REVIEW

**Comment by ceilfors** [comment]
Thanks for submitting this PR @rodrigc! I can see in Jenkins that there's a build failure. I'm still waiting for my IntelliJ licence before I can look into this issue.

**Comment by rodrigc** [comment]
@ceilfors when you get your license, if you can take this over, that would be great.  The jira libraries have changed a lot.

**Comment by asekra** [comment]
> Thanks for submitting this PR @rodrigc! I can see in Jenkins that there's a build failure. I'm still waiting for my IntelliJ licence before I can look into this issue.

Hi Any plan of merging this PR? plugin is not working with recent jira cloud GDPR changes

**Comment by rodrigc** [comment]
@asekra This PR needs more work to make all the tests pass.  I'm not familiar enough with the code, and I don't actively use this plugin, so would not some help from interested contributors.

**Comment by zztalker** [comment]
@rodrigc I've made PR to your fork, could you take a look?

**Pull request merged**
